[project]
name = "campus-placement-predictor"
version = "1.0.0"
description = "A machine learning project to predict campus placements."
authors = [{ name = "Sai Kushal Ranga" }]
requires-python = ">=3.10"
dependencies = [
    "streamlit",
    "scikit-learn",
    "numpy",
    "pandas"
]